name: nri-postgresql
synopsis: Make queries against Postgresql.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-postgresql#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-postgresql#readme
author: NoRedInk
version: 0.1.0.4
maintainer: haskell-open-source@noredink.com
copyright: 2022 NoRedInk Corp.
github: NoRedInk/haskell-libraries/postgresql
license-file: LICENSE
category: Web
extra-doc-files:
- README.md
- LICENSE
- CHANGELOG.md
extra-source-files:
- "test/golden-results/*.json"
dependencies:
- attoparsec >= 0.13.0.0
- base >= 4.16.3.0
- bytestring >= 0.10.8.2
- filepath >= 1.4.2.1
- network >= 3.1.0.0
- nri-env-parser >= 0.1.0.0
- nri-observability >= 0.1.0.0
- nri-prelude >= 0.1.0.0
- postgresql-typed >= 0.6
- resource-pool >= 0.2.0.0
- resourcet >= 1.2.0
- safe-exceptions >= 0.1.7.0
- template-haskell >= 2.15.0.0
- text >= 1.2.3.1
- time >= 1.8.0.2
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
library:
  exposed-modules:
  - Postgres
  - Postgres.Enum
  - Postgres.Test
  source-dirs: src
tests:
  tests:
    main: Main.hs
    source-dirs:
    - src
    - test
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
    default-extensions:
      - ExtendedDefaultRules
    dependencies:
      - th-test-utils
