language: nix
nix: 2.3.7
os: linux
dist: xenial
env:
  global:
    - PGPORT=8088
    - CACHIX_CACHE=nri-open-source
install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix use $CACHIX_CACHE
script:
  - cachix watch-exec $CACHIX_CACHE -- nix-shell shell-ghc-8-10.nix --run "./run-tests.sh"
