language: nix
nix: 2.3.7
sudo: false
env:
  global:
    - CACHIX_CACHE=nri-open-source
install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix use $CACHIX_CACHE
  - nix path-info --all > /tmp/store-path-pre-build
script:
  - nix-shell shell-ghc-8-10.nix --run "./run-tests.sh"
  - nix-shell shell-ghc-8-8.nix --run "./run-tests.sh"
after_success:
  - comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_CACHE
