language: nix
nix: 2.17.0
os: linux
dist: xenial
vm:
  # we were getting out of memory errors without this
  size: large
env:
  global:
    - PGPORT=8088
    - CACHIX_CACHE=nri
  jobs:
    - GHC_VERSION=8-10
    - GHC_VERSION=9-2
install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix use $CACHIX_CACHE
script:
  - cachix watch-exec $CACHIX_CACHE -- nix-shell shell-ghc-$GHC_VERSION.nix --run "./run-tests.sh"
