<<: !include ../package-yaml-support/base-package.yaml
name: database
synopsis: NRI helper for database queries
extra-source-files:
- README.md
dependencies:
- attoparsec
- async
- base
- bytestring
- directory
- env-parser
- exceptions
- filepath
- health
- lens
- lens-regex-pcre
- monad-logger
- mysql-haskell
- mtl
- network
- nri-prelude
- oops
- persistent-mysql-haskell
- pcre-light
- postgresql-simple
- postgresql-typed
- process
- resource-pool
- resourcet
- safe-exceptions
- template-haskell
- text
- time
- typed-process
- unix
library:
  exposed-modules:
  - MySQL
  - Postgres
  - DatabaseSpec
  source-dirs: src
tests:
  unit:
    dependencies:
    - hedgehog
    - database
    - tasty
    - tasty-ant-xml
    - tasty-hedgehog
    - tasty-hunit
    main: Main.hs
    source-dirs:
    - test/unit
    ghc-options: *test-ghc-options
