<<: !include ../package-yaml-support/base-package.yaml
name: http
synopsis: Make Elm style HTTP requests
extra-source-files:
- README.md
library:
  dependencies:
  - aeson
  - base
  - bytestring
  - cherry-core
  - conduit
  - http-client
  - http-client-tls
  - http-types
  - mime-types
  - network-uri
  - text
  exposed-modules:
  - Http
  source-dirs: src
