<<: !include ../package-yaml-support/base-package.yaml
name: http
synopsis: Make Elm style HTTP requests
extra-source-files:
- README.md
library:
  dependencies:
  - aeson
  - base
  - bytestring
  - cherry-core
  - conduit
  - http-client
  - http-client-tls
  - http-types
  - mime-types
  - network-uri
  - safe-exceptions
  - text
  exposed-modules:
  - Http
  source-dirs: src
tests:
  spec:
    dependencies:
    - base
    - bytestring
    - cherry-core
    - conduit
    - http
    - http-types
    - safe-exceptions
    - text
    - wai
    - warp
    main: Main.hs
    source-dirs:
    - test/
    # We intentionally do not add the default ghc-options for tests. These would
    # cause tests to run in parallel, which introduces flakiness in this test
    # suite. The suite creates a number of web servers that are supposed to get
    # unique ports, but if we start them in parallel this will not always work.
