name: nri-redis
synopsis: An intuitive hedis wrapper library.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-redis#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-redis#readme
author: NoRedInk
version: 0.1.0.4
maintainer: haskell-open-source@noredink.com
copyright: 2022 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-redis
license-file: LICENSE
category: Web
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
dependencies:
  - aeson >= 1.4.6.0
  - async >=2.2.2
  - base >= 4.16.3.0
  - bytestring >= 0.10.8.2
  - conduit >= 1.3.0
  # hedis 14 introduces redis-cluster support
  - hedis >= 0.14.0
  - nri-env-parser >= 0.1.0.0
  - nri-observability >= 0.1.0
  - nri-prelude >= 0.1.0.0
  - pcre-light >= 0.4.1.0
  - resourcet >= 1.2.0
  - safe-exceptions >= 0.1.7.0
  - text >= 1.2.3.1
  - unordered-containers >=0.2.0.0
  - uuid >=1.3.0
library:
  exposed-modules:
    - NonEmptyDict
    - Redis
    - Redis.Counter
    - Redis.Hash
    - Redis.List
    - Redis.Mock
    - Redis.Set
  source-dirs:
    - src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fno-warn-type-defaults
  - -fplugin=NriPrelude.Plugin
tests:
  tests:
    main: Main.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
