name: nri-http
synopsis: Make Elm style HTTP requests
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-http#readme>.
author: NoRedInk
version: 0.1.0.2
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-http
license-file: LICENSE
category: Web
extra-source-files:
  - README.md
  - LICENSE
  - "test/golden-results/*.json"
library:
  dependencies: &dependencies
  - aeson
  - base
  - bytestring
  - nri-prelude
  - nri-observability
  - conduit
  - http-client
  - http-client-tls
  - http-types
  - mime-types
  - network-uri
  - safe-exceptions
  - text
  - wai
  - warp
  exposed-modules:
  - Http
  - Http.Mock
  source-dirs: src
tests:
  spec:
    dependencies: *dependencies
    main: Main.hs
    source-dirs:
    - src
    - test
    # We intentionally do not add the default ghc-options for tests. These would
    # cause tests to run in parallel, which introduces flakiness in this test
    # suite. The suite creates a number of web servers that are supposed to get
    # unique ports, but if we start them in parallel this will not always work.
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
