name: nri-http
synopsis: Make Elm style HTTP requests
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-http#readme>.
author: NoRedInk
version: 0.3.0.0
maintainer: haskell-open-source@noredink.com
copyright: 2022 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-http
license-file: LICENSE
category: Web
extra-source-files:
  - README.md
  - LICENSE
  - "test/golden-results/*"
library:
  dependencies:
  - aeson >= 1.4.6.0
  - base >= 4.16.3.0
  - bytestring >= 0.10.8.2
  - case-insensitive >= 1.2.1.0
  - nri-prelude >= 0.1.0.0
  - nri-observability >= 0.1.0.0
  - conduit >= 1.3.0
  - http-client >= 0.6.0
  - http-client-tls >= 0.3.0
  - http-types >= 0.12
  - mime-types >= 0.1.0.0
  - network-uri >= 2.6.0.0
  - safe-exceptions >= 0.1.7.0
  - text >= 1.2.3.1
  exposed-modules:
  - Http
  - Http.Mock
  source-dirs: src
tests:
  spec:
    dependencies:
    - aeson >= 1.4.6.0
    - base >= 4.12.0.0
    - bytestring >= 0.10.8.2
    - case-insensitive >= 1.2.1.0
    - nri-prelude >= 0.1.0.0
    - nri-observability >= 0.1.0.0
    - conduit >= 1.3.0
    - http-client >= 0.6.0
    - http-client-tls >= 0.3.0
    - http-types >= 0.12
    - mime-types >= 0.1.0.0
    - network-uri >= 2.6.0.0
    - safe-exceptions >= 0.1.7.0
    - text >= 1.2.3.1
    - wai >= 3.2.0
    - warp >= 3.3.0
    main: Main.hs
    source-dirs:
    - src
    - test
    # We intentionally do not add threaded ghc-options for tests. These would
    # cause tests to run in parallel, which introduces flakiness in this test
    # suite. The suite creates a number of web servers that are supposed to get
    # unique ports, but if we start them in parallel this will not always work.
    ghc-options:
      - -fno-warn-type-defaults
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
  - ExtendedDefaultRules
  - NumericUnderscores
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
