name: nri-test-encoding
synopsis: A library to simplify writing golden tests for encoding types.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-test-encoding#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-test-encoding#readme
author: NoRedInk
version: 0.1.1.0
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-test-encoding
license-file: LICENSE
category: Testing
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
library:
  dependencies: &dependencies
    - aeson >= 1.4.6.0 && < 1.6
    - aeson-pretty >=0.8.0 && < 0.9
    - base >= 4.12.0.0 && < 4.16
    - bytestring >= 0.10.8.2 && < 0.12
    - filepath >= 1.4.2.1 && < 1.5
    - servant >= 0.16.2 && < 0.19
    - servant-auth-server >= 0.4.5.1 && < 0.5
    - servant-server >= 0.16.2 && < 0.19
    - text >= 1.2.3.1 && < 1.3
    - nri-prelude >= 0.1.0.0 && < 0.7
    - nri-redis >= 0.1.0.0 && < 0.2
  exposed-modules:
    - Examples
    - Test.Encoding
    - Test.Encoding.Routes
    - Redis.Test
  source-dirs:
    - src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
