name: nri-test-encoding
synopsis: A library to simplify writing golden tests for encoding types.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-test-encoding#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-test-encoding#readme
author: NoRedInk
version: 0.2.0.1
maintainer: haskell-open-source@noredink.com
copyright: 2023 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-test-encoding
license-file: LICENSE
category: Testing
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
dependencies:
  - aeson >= 2.0 && < 2.2
  - aeson-pretty >=0.8.0 && < 0.9
  - base >= 4.16.4.0 && < 4.18
  - bytestring >= 0.10.8.2 && < 0.12
  - filepath >= 1.4.2.1 && < 1.5
  - servant >= 0.16.2 && < 0.21
  - servant-auth-server >= 0.4.5.1 && < 0.5
  - servant-server >= 0.16.2 && < 0.21
  - text >= 1.2.3.1 && < 2.1
  - nri-prelude >= 0.1.0.0 && < 0.7
  - nri-redis >= 0.1.0.0 && < 0.3
library:
  exposed-modules:
    - Examples
    - Test.Encoding
    - Test.Encoding.Redis
    - Test.Encoding.Routes
  source-dirs:
    - src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
tests:
  tests:
    main: Main.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
