name: env-parser
synopsis: Read environment variables as settings to build 12-factor apps.
author: NoRedInk
version: '0.1.0.0'
maintainer: haskell-open-source@noredink.com
copyright: 2020 NoRedInk Corp.
homepage: https://github.com/NoRedInk/haskell-libraries
license-file: LICENSE
extra-source-files:
  - README.md
  - LICENSE
library:
  dependencies:
    - base >= 4.12.0.0 && < 4.13
    - nri-prelude >= 0.1.0.0 && < 0.2
    - containers >= 0.6.0.1 && < 0.7
    - modern-uri >= 0.3.1.0 && < 0.4
    - network-uri >= 2.6.2.0 && < 2.8
    - text >= 1.2.3.1 && < 1.3
  exposed-modules:
    - Environment
  source-dirs: src
default-extensions:
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- ScopedTypeVariables
- Strict
- TypeOperators
ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
