name: nri-kafka
synopsis: Functions for working with Kafka
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-kafka#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-kafka#readme
author: NoRedInk
version: 0.1.0.4
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-kafka
license-file: LICENSE
category: Web
extra-source-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
dependencies:
  - aeson >= 1.4.6.0 && < 2.1
  - async >=2.2.2 && <2.3
  - base >= 4.12.0.0 && < 4.17
  - bytestring >= 0.10.8.2 && < 0.12
  - conduit >= 1.3.0 && < 1.4
  - containers >= 0.6.0.1 && < 0.7
  - hw-kafka-client >=4.0.3 && < 5.0
  - nri-env-parser >= 0.1.0.0 && < 0.2
  - nri-observability >= 0.1.1.1 && < 0.2
  - nri-prelude >= 0.1.0.0 && < 0.7
  - safe-exceptions >= 0.1.7.0 && < 1.3
  - stm >= 2.4 && < 2.6
  - text >= 1.2.3.1 && < 2.1
  - time >= 1.8.0.2 && < 2
  - unix >= 2.7.2.2 && < 2.8.0.0
  - uuid >=1.3.0 && < 1.4
library:
  exposed-modules:
    - Kafka
    - Kafka.Worker
    - Kafka.Test
  source-dirs: src
tests:
  tests:
    main: Main.hs
    source-dirs:
      - src
      - test
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
default-extensions:
  - DataKinds
  - DeriveGeneric
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fno-warn-type-defaults
  - -fplugin=NriPrelude.Plugin
