name: nri-observability
synopsis: Report log spans collected by nri-prelude.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/observability>.
author: NoRedInk
version: 0.1.0.1
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-libraries/observability
license-file: LICENSE
category: Web
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
library:
  dependencies: &dependencies
    - aeson >= 1.4.6.0 && < 1.6
    - aeson-pretty >= 0.8.0 && < 0.9
    - async >= 2.2.2 && < 2.3
    - base >= 4.12.0.0 && < 4.16
    - bugsnag-hs >= 0.1.0.0 && < 0.3
    - bytestring >= 0.10.8.2 && < 0.12
    - directory >= 1.3.3.0 && < 1.4
    - http-client >= 0.6.0 && < 0.8
    - http-client-tls >= 0.3.0 && < 0.4
    - hostname >= 1.0 && < 1.1
    - nri-env-parser >= 0.1.0.0 && < 0.2
    - nri-prelude >= 0.1.0.0 && < 0.6
    - random >= 1.1 && < 1.3
    - unordered-containers >= 0.2.0.0 && < 0.3
    - safe-exceptions >= 0.1.7.0 && < 1.3
    - stm >= 2.4 && < 2.6
    - text >= 1.2.3.1 && < 1.3
    - time >= 1.8.0.2 && < 1.12
  exposed-modules:
    - Log.HttpRequest
    - Log.RedisCommands
    - Log.SqlQuery
    - Reporter.Bugsnag
    - Reporter.Dev
    - Reporter.File
  source-dirs: src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
tests:
  tests:
    dependencies: *dependencies
    main: Main.hs
    source-dirs:
      - tests
      - src
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
    default-extensions:
      - ExtendedDefaultRules
