name: nri-observability
synopsis: Report log spans collected by nri-prelude.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/observability>.
author: NoRedInk
version: 0.1.0.0
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-libraries/observability
license-file: LICENSE
category: Web
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
library:
  dependencies:
    - aeson >= 1.4.6.0 && < 1.6
    - base >= 4.12.0.0 && < 4.15
    - nri-prelude >= 0.1.0.0 && < 0.5
  exposed-modules:
    - Log.MySql
  source-dirs: src
default-extensions:
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- ScopedTypeVariables
- Strict
- TypeOperators
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
- -fplugin=NriPrelude.Plugin
