name: nri-observability
synopsis: Report log spans collected by nri-prelude.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-observability#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-observability#readme
author: NoRedInk
version: 0.1.1.4
maintainer: haskell-open-source@noredink.com
copyright: 2022 NoRedInk Corp.
github: NoRedInk/haskell-libraries/observability
license-file: LICENSE
category: Web
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
dependencies:
  - aeson >= 1.4.6.0
  - aeson-pretty >= 0.8.0
  - async >= 2.2.2
  - base >= 4.16.3.0
  - bugsnag-hs >= 0.2.0.9
  - bytestring >= 0.10.8.2
  - conduit >= 1.3.0
  - directory >= 1.3.3.0
  - http-client >= 0.6.0
  - http-client-tls >= 0.3.0
  - hostname >= 1.0
  - nri-env-parser >= 0.1.0.0
  - nri-prelude >= 0.1.0.0
  - random >= 1.1
  - unordered-containers >= 0.2.0.0
  - safe-exceptions >= 0.1.7.0
  - stm >= 2.4
  - text >= 1.2.3.1
  - time >= 1.8.0.2
  - uuid >=1.3.0
library:
  exposed-modules:
    - Log.HttpRequest
    - Log.RedisCommands
    - Log.SqlQuery
    - Log.Kafka
    - Reporter.Bugsnag
    - Reporter.Dev
    - Reporter.File
    - Reporter.Honeycomb
    - Observability
  source-dirs: src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
tests:
  tests:
    main: Main.hs
    source-dirs:
      - tests
      - src
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
    default-extensions:
      - ExtendedDefaultRules
