name: nri-prelude
synopsis: A Prelude inspired by the Elm programming language
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-prelude#readme>.
homepage: https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-prelude#readme
author: NoRedInk
version: 0.6.1.2
maintainer: haskell-open-source@noredink.com
copyright: 2023 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-prelude
license-file: LICENSE
category: Web
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
  - licenses/ELM_CORE_LICENSE
  - licenses/ELM_TEST_LICENSE
library:
  dependencies: &dependencies
    - aeson >= 1.4.6.0 && < 2.2
    - aeson-pretty >= 0.8.0 && < 0.9
    - async >= 2.2.2 && < 2.3
    - attoparsec >= 0.13.0.0 && < 0.15
    - auto-update >= 0.1.6 && < 0.2
    - base >= 4.12.0.0 && < 4.18
    - bytestring >= 0.10.8.2 && < 0.12
    - containers >= 0.6.0.1 && < 0.7
    - directory >= 1.3.3.0 && < 1.4
    - exceptions >= 0.10.4 && < 0.11
    - filepath >= 1.4.2.1 && < 1.5
    - ghc >= 8.6.1 && < 9.8
    - hedgehog >= 1.0.2 && < 1.3
    - junit-xml >= 0.1.0.0 && < 0.2.0.0
    - lens >=4.16.1 && <5.3
    - pretty-diff >= 0.4.0.2 && < 0.5
    - pretty-show >= 1.9.5 && < 1.11
    - safe-coloured-text >= 0.1.0.0 && < 0.3
    - safe-coloured-text-terminfo >= 0.0.0.0 && < 0.2
    - safe-exceptions >= 0.1.7.0 && < 1.3
    - terminal-size >= 0.3.2.1 && < 0.4
    - text >= 1.2.3.1 && < 2.1
    - time >= 1.8.0.2 && < 2
    - unix >= 2.7.2.2 && < 2.8.0.0
    - vector >= 0.12.1.2 && < 0.13
  exposed-modules:
    - Array
    - Basics
    - Bitwise
    - Char
    - Debug
    - Dict
    - Expect
    - Fuzz
    - List
    - Log
    - Maybe
    - NriPrelude
    - NriPrelude.Plugin
    - Platform
    - Process
    - Result
    - Set
    - Task
    - Test
    - Text
    - Tuple
  source-dirs:
    - src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
tests:
  tests:
    dependencies: *dependencies
    main: Main.hs
    source-dirs:
      - tests
      - src
    ghc-options:
      - -threaded
      - -rtsopts "-with-rtsopts=-N -T"
      - -fno-warn-type-defaults
    default-extensions:
      - ExtendedDefaultRules
