name: nri-prelude
synopsis: A Prelude inspired by the Elm programming language
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/nri-prelude>.
author: NoRedInk
version: 0.1.0.2
maintainer: haskell-open-source@noredink.com
copyright: 2020 NoRedInk Corp.
github: NoRedInk/haskell-libraries/nri-prelude
license-file: LICENSE
category: Web
extra-doc-files:
- README.md
- LICENSE
- CHANGELOG.md
- licenses/ELM_CORE_LICENSE
- licenses/ELM_TEST_LICENSE
library:
  dependencies: &dependencies
  - aeson >= 1.4.6.0 && < 1.6
  - ansi-terminal >= 0.9.1 && < 0.12
  - async >= 2.2.2 && < 2.3
  - auto-update >= 0.1.6 && < 0.2
  - base >= 4.12.0.0 && < 4.15
  - bytestring >= 0.10.8.2 && < 0.12
  - concurrent-output >= 1.10.11 && < 1.11
  - containers >= 0.6.0.1 && < 0.7
  - directory >= 1.3.3.0 && < 1.4
  - exceptions >= 0.10.4 && < 0.11
  - filepath >= 1.4.2.1 && < 1.5
  - hedgehog >= 1.0.2 && < 1.1
  - junit-xml >= 0.1.0.0 && < 0.2
  - pretty-diff >= 0.1.0.0 && < 0.3
  - pretty-show >= 1.9.5 && < 1.11
  - resourcet >= 1.2.2 && < 1.3
  - safe-exceptions >= 0.1.7.0 && < 1.3
  - tasty >= 1.2.3 && < 1.4
  - tasty-test-reporter >= 0.1.1.1 && < 0.2
  - terminal-size >= 0.3.2.1 && < 0.4
  - text >= 1.2.3.1 && < 1.3
  - time >= 1.8.0.2 && < 1.11
  - vector >= 0.12.1.2 && < 0.13
  exposed-modules:
  - Array
  - Basics
  - Bitwise
  - Char
  - Debug
  - Dict
  - Expect
  - Expect.Task
  - Fuzz
  - List
  - Log
  - Maybe
  - NriPrelude
  - Platform
  - Process
  - Result
  - Set
  - Task
  - Test
  - Test.Runner.Tasty
  - Text
  - Tuple
  source-dirs:
  - src
default-extensions:
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- ScopedTypeVariables
- Strict
- TypeOperators
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
tests:
  tests:
    dependencies: *dependencies
    main: Main.hs
    source-dirs:
    - tests
    - src
    ghc-options:
    - -threaded
    - -rtsopts "-with-rtsopts=-N -T"
