name: nri-env-parser
synopsis: Read environment variables as settings to build 12-factor apps.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/env-parser>.
author: NoRedInk
version: 0.1.0.5
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-libraries/env-parser
license-file: LICENSE
category: Web
extra-doc-files:
  - README.md
  - LICENSE
  - CHANGELOG.md
library:
  dependencies:
    - base >= 4.12.0.0 && < 4.15
    - nri-prelude >= 0.1.0.0 && < 0.6
    - modern-uri >= 0.3.1.0 && < 0.4
    - network-uri >= 2.6.2.0 && < 2.8
    - text >= 1.2.3.1 && < 1.3
  exposed-modules:
    - Environment
  source-dirs: src
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
