name: nri-log-explorer
synopsis: Explore logs produced by nri-prelude tests.
description: Please see the README at <https://github.com/NoRedInk/haskell-libraries/tree/trunk/log-explorer>.
author: NoRedInk
version: 0.1.0.0
maintainer: haskell-open-source@noredink.com
copyright: 2020 NoRedInk Corp.
github: NoRedInk/haskell-libraries/log-explorer
license-file: LICENSE
category: Web
extra-doc-files:
- README.md
- LICENSE
- CHANGELOG.md
executables:
  nri-log-explorer:
    dependencies:
    - aeson >= 1.4.6.0 && < 1.6
    - async >= 2.2.2 && < 2.3
    - base >= 4.12.0.0 && < 4.15
    - brick >= 0.51 && < 1.0
    - bytestring >= 0.10.8.2 && < 0.12
    - directory >= 1.3.3.0 && < 1.4
    - filepath >= 1.4.2.1 && < 1.5
    - nri-prelude >= 0.1.0.0 && < 0.4
    - text >= 1.2.3.1 && < 1.3
    - vty >= 5.0 && < 6.0
    main: Main.hs
    source-dirs: src
default-extensions:
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- ScopedTypeVariables
- Strict
- TypeOperators
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
- -threaded
- -rtsopts "-with-rtsopts=-N -T -xq10m"
- -O2
